spring.application.name=java-bank-portal
server.port=8081
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true

# Thymeleaf
spring.thymeleaf.encoding=UTF-8
spring.thymeleaf.cache=false
spring.thymeleaf.mode=HTML

# Jackson
spring.jackson.default-property-inclusion=non_null
spring.mvc.charset=UTF-8

logging.level.com.bank.portal=INFO
